### PR TITLE
Feature/dvc - Using DVC for our dataset

### PR DESCRIPTION
**Pull request by alexmunozbravo**
Setup DVC and first version link for our Dataset (IMDB Movie Review Dataset).

### CODE REVIEW

**Comment by joelcf001** [comment]
Are interim and processed folders inside data/ necessary in the repository?

**Comment by alexmunozbravo** [comment]
They are not used in our project, but I think they should be there in case external data or further preprocessing is done in the future.

**Review by alexmunozbravo — COMMENTED** [review]
Approvals where made in real life.

**Review by joelcf001 — COMMENTED** [review]
Good work!

**Pull request merged**
